export const POST_CONTACT_REQUEST = 'POST_CONTACT_REQUEST';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_CONTACT_ERROR = 'POST_CONTACT_ERROR';

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';

export const REMOVE_CONTACT_REQUEST = 'REMOVE_CONTACT_REQUEST';
export const REMOVE_CONTACT_SUCCESS = 'REMOVE_CONTACT_SUCCESS';
export const REMOVE_CONTACT_ERROR = 'REMOVE_CONTACT_ERROR';

export const POST_CHANGES_REQUEST = 'POST_CHANGES_REQUEST';
export const POST_CHANGES_SUCCESS = 'POST_CHANGES_SUCCESS';
export const POST_CHANGES_ERROR = 'POST_CHANGES_ERROR';
